version: '3.6'
services:
  mongodb:
    container_name: mongodb
    image: mongo:6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=developmentUsername
      - MONGO_INITDB_ROOT_PASSWORD=developmentPassword
    ports:
      - "27017:27017"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./apps/api/mongo-keyfile:/config/mongo-keyfile
      - type: volume
        source: mongodb
        target: /data/db
    networks:
      - app-network
    entrypoint:
      - bash
      - -c
      - |
        cp /config/mongo-keyfile /config/keyfile
        chmod 400 /config/keyfile
        chown mongodb -R /config/keyfile
        exec docker-entrypoint.sh $$@
    command: mongod --replSet rs --bind_ip_all --keyFile config/keyfile --quiet --logpath /dev/null
volumes:
  mongodb:
networks:
  app-network:
